# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9b9e027b41561ba9293e9a6fa5845d956d937f9a71b32643bf7c5c51ff0d3cdbd288da24faea5f5accf0f21f67e042e9e809435d6d8d96bc8e091fef372d3c2b

test:
  secret_key_base: 0cd7cb1ffe46548a54d59f25e82a398b69fd488e0865c90961b4c568ac930253e27600a51f80bd8b15dc0e1377c3c704132a148bc3f1994f7279d5625ec3b254

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
